security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        SIWOZ\EguardianBundle\Entity\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

   # providers:
       # providers:
       # administrators:
       #     entity: { class: AcmeUserBundle:User }
       ## in_memory:
        ##    memory:
        #        users:
        ##            user:  { password: userpass, roles: [ 'ROLE_USER' ] }
        #            admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        #            
        #            
    providers:
        administrators:
            entity: { class: EguardianBundle:User }
    #providers:
       # siwoz_service:
            #id: user_provider
            

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/demo/secured/login$
            security: false

        secured_area:
            pattern:    ^/place|login
            http_basic: ~
            stateless:  true
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/place, roles: ROLE_USER }
        - { path: ^/login$, roles: ROLE_USER }
        - { path: ^/login/guardian, roles: ROLE_ADMIN}
       # - { path: ^/user, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
