eguardian_welcome:
    pattern:  /
    defaults: { _controller: EguardianBundle:Default:index }
eguardian_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: EguardianBundle:Default:hello }
eguardian_place:
    pattern:  /place/{id}
    defaults: { _controller: EguardianBundle:User:place }
    methods:  [GET]
eguardian_put_place:
    pattern:  /place
    defaults: { _controller: EguardianBundle:User:putPlace }
    methods:  [PUT]
eguardian_put_senior_user:
    pattern:  /user/senior
    defaults: { _controller: EguardianBundle:User:putSeniorUser }
    methods:  [PUT]
eguardian_put_guardian_user:
    pattern:  /user/guardian
    defaults: { _controller: EguardianBundle:User:putGuardianUser }
    methods:  [PUT]    
eguardian_get_user:
    pattern:  /user/{login}
    defaults: { _controller: EguardianBundle:User:getUser }
    methods:  [GET]
eguardian_update_user:
    pattern:  /user
    defaults: { _controller: EguardianBundle:User:updateUser }
    methods:  [POST]
eguardian_update_guardian_user:
    pattern:  /user/guardian
    defaults: { _controller: EguardianBundle:User:updateGuardianUser }
    methods:  [POST]
eguardian_update_senior_user:
    pattern:  /user/senior
    defaults: { _controller: EguardianBundle:User:updateSeniorUser }
    methods:  [POST]
eguardian_update_registration_id:
    pattern:  /user/registrationId
    defaults: { _controller: EguardianBundle:User:updateRegistrationId }
    methods:  [POST]
eguardian_add_guardian_to_senior:
    pattern:  /user/{guardianLogin}/{seniorLogin}
    defaults: { _controller: EguardianBundle:User:addGuardianToSenior }
    methods:  [PUT]
eguardian_remove_guardian_to_senior:
    pattern:  /user/{guardianLogin}/{seniorLogin}
    defaults: { _controller: EguardianBundle:User:removeGuardianToSenior }
    methods:  [DELETE]
eguardian_send_notification:
    pattern:  /send
    defaults: { _controller: EguardianBundle:Notification:send }
    methods:  [GET]
eguardian_send_notification:
    pattern:  /send/event/{id}
    defaults: { _controller: EguardianBundle:Notification:sendEvent }
    methods:  [GET]
eguardian_send_senior_notification:
    pattern:  /send/senior
    defaults: { _controller: EguardianBundle:Notification:sendSeniorNotification }
    methods:  [GET]    
eguardian_login:
    pattern:  /login
    defaults: { _controller: EguardianBundle:User:login }
    methods:  [GET]
eguardian_login_guardian:
    pattern:  /login/guardian
    defaults: { _controller: EguardianBundle:User:login }
    methods:  [GET]
eguardian_event_meal_put:
    pattern:  /event/meal
    defaults: { _controller: EguardianBundle:Event:putMealEvent }
    methods:  [PUT]
eguardian_event_visit_put:
    pattern:  /event/visit
    defaults: { _controller: EguardianBundle:Event:putVisitEvent }
    methods:  [PUT]
eguardian_event_test_put:
    pattern:  /event/test
    defaults: { _controller: EguardianBundle:Event:putTestEvent }
    methods:  [PUT]
eguardian_event_medicine_put:
    pattern:  /event/medicine
    defaults: { _controller: EguardianBundle:Event:putMedicineEvent }
    methods:  [PUT]
eguardian_event_get:
    pattern:  /event/{type}/{id}
    defaults: { _controller: EguardianBundle:Event:getEvent }
    methods:  [GET]    
    requirements:
        type:   meal|visit|medicine|test
eguardian_event_meals_get:
    pattern:  /event/meal
    defaults: { _controller: EguardianBundle:Event:getEvents, className: 'SIWOZ\EguardianBundle\Entity\MealEvent' }
    methods:  [GET]    
eguardian_event_tests_get:
    pattern:  /event/test
    defaults: { _controller: EguardianBundle:Event:getEvents, className: 'SIWOZ\EguardianBundle\Entity\TestEvent' }
    methods:  [GET]    
eguardian_event_visits_get:
    pattern:  /event/visit
    defaults: { _controller: EguardianBundle:Event:getEvents, className: 'SIWOZ\EguardianBundle\Entity\VisitEvent' }
    methods:  [GET]    
eguardian_event_medicines_get:
    pattern:  /event/medicine
    defaults: { _controller: EguardianBundle:Event:getEvents, className: 'SIWOZ\EguardianBundle\Entity\MedicineEvent' }
    methods:  [GET]    
eguardian_event_meals_post:
    pattern:  /event/meal
    defaults: { _controller: EguardianBundle:Event:updateEvent, className: 'SIWOZ\EguardianBundle\Entity\MealEvent' }
    methods:  [POST]    
eguardian_event_tests_post:
    pattern:  /event/test
    defaults: { _controller: EguardianBundle:Event:updateEvent, className: 'SIWOZ\EguardianBundle\Entity\TestEvent' }
    methods:  [POST]    
eguardian_event_visits_post:
    pattern:  /event/visit
    defaults: { _controller: EguardianBundle:Event:updateEvent, className: 'SIWOZ\EguardianBundle\Entity\VisitEvent' }
    methods:  [POST]    
eguardian_event_medicines_post:
    pattern:  /event/medicine
    defaults: { _controller: EguardianBundle:Event:updateEvent, className: 'SIWOZ\EguardianBundle\Entity\MedicineEvent' }
    methods:  [POST]   
eguardian_event_delete:
    pattern:  /event/{type}
    defaults: { _controller: EguardianBundle:Event:deleteEvent }
    methods:  [DELETE]
    requirements:
        type:   meal|visit|medicine|test
eguardian_alarm_put:
    pattern:  /alarm
    defaults: { _controller: EguardianBundle:Alarm:putAlarm }
    methods:  [PUT]
eguardian_alarm_send:
    pattern:  /alarm/send
    defaults: { _controller: EguardianBundle:Alarm:sendAlarms }
    methods:  [GET]
eguardian_notification_guardian_send:
    pattern:  /notification/guardian/send
    defaults: { _controller: EguardianBundle:Notification:sendGuardianNotification }
    methods:  [GET]
eguardian_notification_senior_send:
    pattern:  /notification/senior/send
    defaults: { _controller: EguardianBundle:Notification:sendSeniorNotification }
    methods:  [GET]

