parameters:
#    eguardian.example.class: SIWOZ\EguardianBundle\Example

services:
#    eguardian.example:
#        class: %eguardian.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
